export type TypographyVariant =
  | "h1"
  | "h2"
  | "h3"
  | "h4"
  | "h5"
  | "title1"
  | "title2"
  | "title3"
  | "body1"
  | "body2"
  | "body3"
  | "label1"
  | "label2"
  | "label3"
  | "label4"
  | "caption1"
  | "caption2"
  | "btn-sm"
  | "btn-md"
  | "btn-lg";

export type TypographyColor =
  | "prose-primary"
  | "prose-secondary"
  | "prose-hint"
  | "prose-inverse"
  | "prose-disabled"
  | "prose-link"
  | "prose-white"
  | "brand"
  | "info"
  | "success"
  | "warning"
  | "critical";
